server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
    ddl-auto: update
    show-sql: true


  outbound:
    identity:
      client-id:
      client-secret:
      client-uri:

  jwt:
    signerKey: "N/gwZiN6XIaNjbTIJBcucYPPVm1uYdpiotz1AISKSQEAWywRLkqd4253PPClzbKV"
    valid-duration: 5 #in second
    refreshable-duration: 120 #in seconds

